{{- if .Values.nifi.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kylo.name" . }}-nifi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kylo.name" . }}-nifi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations: 
{{ toYaml .Values.nifi.ingress.annotations | trim | indent 4 }}
spec:
  backend:
    serviceName: {{ template "kylo.fullname" . }}-nifi
    servicePort: {{ .Values.nifi.properties.httpPort }}
  rules:
  - host: {{ .Values.nifi.ingress.domain }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
{{- end -}}
