apiVersion: batch/v1
kind: Job
metadata:
  name: create-elasticsearch-indicies
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 500
  template:
    spec:
      containers:
      - name: create-elasticsearch-indicies
        image: cfmanteiga/alpine-bash-curl-jq:latest
        command: 
          - "bash"
          - "-c"
          - |
            mkdir /tmp/create/
            cp /etc/config/* /tmp/create/
            chmod +x /tmp/create/create-kylo-indexes-es.sh
            while ! curl --output /dev/null --silent --head --fail http://kylo-elasticsearch-client:9200; do sleep 1; done
            ./tmp/create/create-kylo-indexes-es.sh kylo-elasticsearch-client 9200 1 1
        volumeMounts:
          - name: elasticsearch-indicies
            mountPath: /etc/config
      restartPolicy: OnFailure
      volumes:
        - name: elasticsearch-indicies
          configMap:
            name: {{ template "kylo.name" . }}-elasticsearch-indicies
