---
apiVersion: v1
kind: Service
metadata:
  name: hive-server
  labels:
    app: hive-server
spec:
  type: NodePort
  ports:
  - port: 10000
    targetPort: hive-server
    name: hive-server
  selector:
    app: hive-server
