dependencies:
- name: zookeeper
  version: 1.2.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: zookeeper.enabled
- name: elasticsearch
  version: 1.13.0
  repository: https://kubernetes-charts.storage.googleapis.com
