apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-configs
  labels:
    component: presto
{{ include "kdp.labels" . | indent 4 }}
data:
  jmx_exporter_config.yaml: |
    {}

  log.properties: |
    com.facebook.presto={{ .Values.presto.logLevel }}
