---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  type: NodePort
  ports:
  - port: 9083
    targetPort: hive-metastore
    name: hive-metastore
  selector:
    app: hive-metastore
