---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
      - name: init-schema
        image: jeffgrunewald/hive-metastore:1.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        args:
        - /usr/local/hive-metastore/bin/schematool -dbType postgres -validate || /usr/local/hive-metastore/bin/schematool -dbType postgres -initSchema
        volumeMounts:
        - mountPath: /usr/local/hive-metastore/conf/metastore-site.xml
          name: metastore-site
          subPath: metastore-site.xml
      containers:
      - name: hive-metastore
        image: jeffgrunewald/hive-metastore:1.7
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/hive-metastore/bin/start-metastore
        ports:
        - containerPort: 9083
          name: hive-metastore
        volumeMounts:
        - mountPath: /usr/local/hive-metastore/conf/metastore-site.xml
          name: metastore-site
          subPath: metastore-site.xml
        - mountPath: /usr/local/hadoop/etc/hadoop/core-site.xml
          name: hadoop-configs
          subPath: core-site.xml
      volumes:
      - name: metastore-site
        configMap:
          name: metastore-site
      - name: hadoop-configs
        configMap:
          name: hadoop-configs
