---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app: postgres
data:
  init.sql: |-
    CREATE DATABASE metastore;
    CREATE USER hive WITH PASSWORD 'password123';
    GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;
