{{- if .Values.hive.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kdp.hive.fullname" . }}
  labels:
    component: hive
{{ include "kdp.labels" . | indent 4 }}    
spec:
  selector:
    matchLabels:
      component: hive
{{ include "kdp.labels" . | indent 6 }}
  replicas: {{ .Values.hive.deploy.replicas }}
  strategy:
{{ toYaml .Values.presto.deploy.updateStrategy | trim | indent 4 }}
  template:
    metadata:
      labels:
        component: hive
{{ include "kdp.labels" . | indent 8 }}
    spec:
      containers:
      - name: hive
        image: {{ .Values.hive.deploy.container.image }}:{{ .Values.hive.deploy.container.tag }}
        imagePullPolicy: {{ .Values.hive.deploy.container.pullPolicy }}
        workingDir: /opt/hive
        command:
        - /bin/sh
        - -c
        args:
        - 'cp /tmp/hive-site.xml /opt/hive/conf/ && sed -i "s/POD_IP/${POD_IP//./-}/" /opt/hive/conf/hive-site.xml && ./bin/hiveserver2'
        ports:
        - containerPort: {{ .Values.hive.service.port }}
          name: hive
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /tmp/hive-site.xml
          name: hive-site
          subPath: hive-site.xml
        - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          name: core-site
          subPath: core-site.xml
      volumes:
      - name: hive-site
        configMap:
          name: {{ template "kdp.hive.fullname" . }}-config
      - name: core-site
        configMap:
          name: {{ template "kdp.name" . }}-core-site
{{- end }}
